#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
    path: /home
    controller: App\Controller\HomeController::display

contact:
    path: /contact
    controller: App\Controller\HomeController::contact

ecole:
    path: /contact
    controller: App\Controller\HomeController::persons

product:
    path: /product
    controller: App\Controller\HomeController::persons

orders:
    path: /orders
    controller: App\Controller\OrderController::test